"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import { ArrowLeft, Lock, Eye, Database, Bell, Trash2, Globe } from "lucide-react";

const SECTIONS = [
  {
    icon: Database,
    color: "#7C5CFC",
    bg: "rgba(124,92,252,0.12)",
    title: "Information we collect",
    body: "We collect information you provide directly — such as your name, email address, phone number, and financial details — as well as data generated by your use of our platform, including transaction history, device identifiers, and IP addresses.",
  },
  {
    icon: Eye,
    color: "#FC5C7D",
    bg: "rgba(252,92,125,0.12)",
    title: "How we use your data",
    body: "Your data is used to operate and improve DigiBank, verify your identity, process transactions, detect fraud, comply with legal obligations, and — with your consent — send you relevant product updates and offers.",
  },
  {
    icon: Lock,
    color: "#5CF0B0",
    bg: "rgba(92,240,176,0.12)",
    title: "Data security",
    body: "We protect your information using AES-256 encryption at rest and TLS 1.3 in transit. Access to personal data is strictly role-based, audited, and limited to personnel who need it to serve you.",
  },
  {
    icon: Globe,
    color: "#5CC8F0",
    bg: "rgba(92,200,240,0.12)",
    title: "Sharing and third parties",
    body: "We do not sell your personal data. We may share data with trusted service providers (payment processors, identity verification partners) who are contractually bound to protect it, and with regulators when required by law.",
  },
  {
    icon: Bell,
    color: "#FCA75C",
    bg: "rgba(252,167,92,0.12)",
    title: "Cookies and tracking",
    body: "We use strictly necessary cookies to keep you signed in, and optional analytics cookies to understand how people use DigiBank. You can manage your cookie preferences at any time in account settings.",
  },
  {
    icon: Trash2,
    color: "#FC5C7D",
    bg: "rgba(252,92,125,0.12)",
    title: "Your rights",
    body: "You have the right to access, correct, export, or delete the personal data we hold about you. To exercise any of these rights, contact us at privacy@digibank.com and we will respond within 30 days.",
  },
];

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#0A0A0F] text-white">
      {/* Navbar */}
      <header className="sticky top-0 z-50 border-b border-white/5 bg-[#0A0A0F]/80 backdrop-blur-xl">
        <div className="max-w-6xl mx-auto flex items-center justify-between px-6 py-4">
          <Link href="/" className="font-display text-xl font-black tracking-tight">
            Digi<span className="text-[#7C5CFC]">Bank</span>
          </Link>
          <Link
            href="/"
            className="flex items-center gap-2 text-[13px] font-medium text-white/50 hover:text-white transition-colors duration-200"
          >
            <ArrowLeft className="w-4 h-4" /> Back home
          </Link>
        </div>
      </header>

      {/* Hero */}
      <section className="relative max-w-3xl mx-auto px-6 pt-20 pb-12 text-center">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[500px] h-[300px] bg-[#7C5CFC]/15 rounded-full blur-[100px] pointer-events-none" />
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.45 }}
          className="relative"
        >
          <div className="inline-flex items-center gap-2 bg-white/5 border border-white/10 text-[12px] font-medium text-white/60 px-4 py-1.5 rounded-full mb-6">
            <Lock className="w-3.5 h-3.5 text-[#5CF0B0]" />
            Last updated — January 2026
          </div>
          <h1 className="font-display text-[52px] sm:text-[64px] font-black tracking-tighter leading-[0.95] mb-5">
            Your{" "}
            <span className="bg-gradient-to-r from-[#5CF0B0] via-[#7C5CFC] to-[#FC5C7D] bg-clip-text text-transparent">
              privacy
            </span>
            <br />matters to us.
          </h1>
          <p className="text-[15px] text-white/45 max-w-md mx-auto leading-relaxed">
            We believe privacy is a right, not a feature. Here's exactly what data we collect, why, and how we protect it.
          </p>
        </motion.div>
      </section>

      {/* Commitment strip */}
      <div className="max-w-3xl mx-auto px-6 mb-12">
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="grid grid-cols-3 gap-px bg-white/5 rounded-2xl overflow-hidden border border-white/5"
        >
          {[
            { stat: "0", label: "Data sold" },
            { stat: "AES-256", label: "Encryption standard" },
            { stat: "30 days", label: "Data request SLA" },
          ].map(({ stat, label }) => (
            <div key={label} className="bg-[#0A0A0F] py-6 text-center">
              <p className="font-display text-[22px] font-black text-[#7C5CFC]">{stat}</p>
              <p className="text-[11px] text-white/30 mt-1 uppercase tracking-widest">{label}</p>
            </div>
          ))}
        </motion.div>
      </div>

      {/* Sections */}
      <main className="max-w-3xl mx-auto px-6 pb-24 space-y-4">
        {SECTIONS.map(({ icon: Icon, color, bg, title, body }, i) => (
          <motion.div
            key={title}
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.06 * i + 0.15 }}
            className="group rounded-2xl bg-white/3 hover:bg-white/[0.05] border border-white/[0.06] hover:border-white/[0.1] px-7 py-6 transition-all duration-200"
          >
            <div className="flex items-start gap-4">
              <div
                className="shrink-0 w-10 h-10 rounded-xl flex items-center justify-center mt-0.5 transition-transform duration-200 group-hover:scale-110"
                style={{ backgroundColor: bg }}
              >
                <Icon className="h-5 w-5" style={{ color }} />
              </div>
              <div>
                <h2 className="font-display text-[17px] font-black text-white mb-2">{title}</h2>
                <p className="text-[14px] text-white/50 leading-relaxed">{body}</p>
              </div>
            </div>
          </motion.div>
        ))}

        {/* Contact prompt */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.55 }}
          className="rounded-2xl bg-gradient-to-br from-[#7C5CFC]/15 to-[#FC5C7D]/10 border border-[#7C5CFC]/25 px-7 py-7 text-center"
        >
          <p className="font-display text-[20px] font-black text-white mb-2">Questions about your data?</p>
          <p className="text-[13px] text-white/50 mb-5">Our privacy team is here to help.</p>
          <a
            href="mailto:privacy@digibank.com"
            className="inline-flex items-center gap-2 bg-[#7C5CFC] hover:bg-[#6B4EE6] text-white text-[13px] font-semibold px-6 py-2.5 rounded-xl transition-all duration-200 hover:scale-105 hover:shadow-[0_0_24px_rgba(124,92,252,0.45)] active:scale-95"
          >
            privacy@digibank.com
          </a>
        </motion.div>
      </main>

      {/* Footer strip */}
      <div className="border-t border-white/5">
        <div className="max-w-3xl mx-auto px-6 py-8 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-[12px] text-white/25">© 2026 DigiBank. All rights reserved.</p>
          <div className="flex items-center gap-6">
            <Link href="/terms" className="text-[12px] text-white/40 hover:text-white transition-colors">Terms of Service</Link>
            <Link href="/contact" className="text-[12px] text-white/40 hover:text-white transition-colors">Contact Us</Link>
          </div>
        </div>
      </div>
    </div>
  );
}